urls.py
from django.urls import path, include
from cotizantes import views

app_name='cotizantes'
urlpatterns = [
    path('', views.CotizantesListView.as_view(), name='cotizantes-list'),
    path('add/', views.CotizantesCreateView.as_view(), name='cotizantes-add'),
    path('<int:pk>/detail', views.CotizantesDetailView.as_view(), name='cotizantes-detail'),
    path('<int:pk>/detail1', views.CotizantesDetailView1.as_view(), name='cotizantes-detail1'),
    path('<int:pk>/update', views.CotizantesUpdateView.as_view(), name='cotizantes-update'),
    path('<int:pk>/delete', views.CotizantesDeleteView.as_view(), name='cotizantes-delete'),
]

models.py
from django.db import models

# Create your models here.

from tkinter import Widget

class Cotizantes(models.Model):
    ente = models.CharField(max_length=12, default="", null=False)
    periodo = models.CharField(max_length=6, default="", null=False)
    ficha = models.IntegerField(default=0)
    nombre = models.CharField(max_length=40, default="", null=False)
    dni = models.IntegerField(default=0)
    cuil = models.IntegerField(default=0)
    repa = models.IntegerField(default=0)
    loca = models.IntegerField(default=0)
    importe = models.FloatField(default=0)
    detalle = models.CharField(max_length=20, default="")
    afiliado = models.IntegerField(default=0)
    
    def __str__(self):
        return f'Cotizante: {self.nombre} -- DNI: {self.dni} -- Repa: {self.repa} -- Loca: {self.loca} -- Importe: {self.importe}'

views.py
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from cotizantes.models import Cotizantes
from user.models import Avatar

class CotizantesListView(ListView):
    model = Cotizantes
    template_name = "cotizantes_list.html"

class CotizantesDetailView(DetailView):
    model = Cotizantes
    template_name = "cotizantes_detail.html"
    fields = ['ente', 'periodo', 'ficha','nombre', 'dni', 'cuil','repa', 'loca', 'importe', 'detalle', 'afiliado']

class CotizantesDetailView1(DetailView):
    model = Cotizantes
    template_name = "cotizantes_detail1.html"
    fields = ['ente', 'periodo', 'ficha','nombre', 'dni', 'cuil','repa', 'loca', 'importe', 'detalle', 'afiliado']

class CotizantesCreateView(LoginRequiredMixin, CreateView):
    model = Cotizantes
    template_name = "cotizantes_add.html"
    success_url = reverse_lazy('cotizantes:cotizantes-list')
    fields = ['ente', 'periodo', 'ficha','nombre', 'dni', 'cuil','repa', 'loca', 'importe', 'detalle', 'afiliado']


class CotizantesUpdateView(LoginRequiredMixin, UpdateView):
    model = Cotizantes
    template_name = "cotizantes_form.html"
    success_url = reverse_lazy('cotizantes:cotizantes-list')
    fields = ['ente', 'periodo', 'ficha','nombre', 'dni', 'cuil','repa', 'loca', 'importe', 'detalle', 'afiliado']


class CotizantesDeleteView(LoginRequiredMixin, DeleteView):
    model = Cotizantes
    template_name = "cotizantes_confirm_delete.html"
    success_url = reverse_lazy('cotizantes:cotizantes-list')

templates/cotizantes_add.html
{% extends "index.html" %}
{% load static %}
{% block ProjectManeiro_content %}

<h2>Formulario para crear cotizantes</h2>
<hr></hr>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-azul" value="Crear cotizante" />
</form>

{% endblock %}

templates/cotizantes_confirm_delete.html
{% extends "index.html" %}
{% load static %}
{% block ProjectManeiro_content %}

{% if user.is_superuser %}

<h2>Eliminar Cotizante</h2>
<hr></hr>

<p>Estás seguro de eliminar el cotizante: {{ cotizante.nombre }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-azul" type="submit" value="Si, eliminar.">
    <a class="btn2 btn-primary" href="{% url 'cotizantes:cotizantes-list' %}" >Cancelar</a>
</form>
{% else %}
<br><br>
<table border="1" bgcolor="darkred">
    <thead>
        <th><br><h2 style="color:white" >&nbsp&nbspUSTED NO PUEDE ELIMINAR COTIZANTES&nbsp&nbsp</h2><br></th>
    </thead>
</table>
{%endif%}

{% endblock %}

templates/cotizantes_detail.html
{% extends "index.html" %}
{% load static %}
{% block ProjectManeiro_content %}

<h4>Detalle del Cotizante</h4>
<hr></hr>
<p><h6>Ente: {{ cotizantes.ente }}</h6></p>
<p><h6>Periodo: {{ cotizantes.periodo }}</h6></p>
<p><h6>Ficha: {{ cotizantes.ficha }}</h6></p>
<p><h6>Nombre: {{ cotizantes.nombre }}</h6></p>
<p><h6>DNI: {{ cotizantes.dni }}</h6></p>
<p><h6>Reparticion: {{ cotizantes.repa }}</h6></p>
<p><h6>Lugar de Pago: {{ cotizantes.loca }}</h6></p>
<p><h6>Importe: {{ cotizantes.importe }}</h6></p>
<p><h6>Detalle: {{ cotizantes.detalle }}</h6></p>
<p><h6>Afiliado: {{ cotizantes.afiliado }}</h6></p>
<p><a class="btn btn-azul" href="{% url 'cotizantes:cotizantes-list' %}">Regresar a la lista de cotizantes</a></p>
{% endblock %}

templates/cotizantes_detail1.html
{% extends "index.html" %}
{% load static %}
{% block ProjectManeiro_content %}

<h4>Detalle del Cotizante</h4>
<hr></hr>
<p><h6>Ente: {{ cotizantes.ente }}</h6></p>
<p><h6>Periodo: {{ cotizantes.periodo }}</h6></p>
<p><h6>Ficha: {{ cotizantes.ficha }}</h6></p>
<p><h6>Nombre: {{ cotizantes.nombre }}</h6></p>
<p><h6>DNI: {{ cotizantes.dni }}</h6></p>
<p><h6>Reparticion: {{ cotizantes.repa }}</h6></p>
<p><h6>Lugar de Pago: {{ cotizantes.loca }}</h6></p>
<p><h6>Importe: {{ cotizantes.importe }}</h6></p>
<p><h6>Detalle: {{ cotizantes.detalle }}</h6></p>
<p><h6>Afiliado: {{ cotizantes.afiliado }}</h6></p>
<p><a class="btn btn-azul" href="{% url 'home:main' %}">Regresar a la busqueda</a></p>
{% endblock %}

templates/cotizantes_form.html
{% extends "index.html" %}
{% load static %}
{% block ProjectManeiro_content %}

<h2>Formulario para guardar/editar cotizante</h2>
<hr></hr>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-azul" value="Guardar cotizante" />
</form>

{% endblock %}

templates/cotizantes_list.html
{% extends "index.html" %}
{% load static %}
{% block ProjectManeiro_content %}

{% if user.is_authenticated %}
<h2>Listado de Cotizantes - (Ctrl-F = Busqueda)</h2>
<!-- <a class="btn btn-azul" href="{% url 'cotizantes:cotizantes-add' %}">Crear nuevo cotizante</a> -->

{% endif %}
<hr></hr>
<ul>{% if user.is_authenticated %}
    {% for cotizantes in cotizantes_list %}
    <li>
        {{cotizantes}}
        (
            <a href="{% url 'cotizantes:cotizantes-detail' cotizantes.id %}">
                <i class="fa fa-eye" style="color:greenyellow"> </i>
            </a>
        <!-- |
        <a href="{% url 'cotizantes:cotizantes-update' cotizantes.id %}">
            <i class="fa fa-pencil" style="color:gold"> </i>
        </a>
        |
        <a href="{% url 'cotizantes:cotizantes-delete' cotizantes.id %}">
            <i class="fa fa-trash" style="color:red"> </i>
        </a> -->
        )
    </li>
    {% endfor %}
    {% else %}
    <br>
    <table border="1" bgcolor="darkred">
        <thead>
            <th><br><h2 style="color:white" >&nbsp&nbspDEBE IDENTIFICARSE COMO USUARIO&nbsp&nbsp</h2><br></th>
        </thead>
    </table>
    <br>
    {% endif %}
</ul>

{% endblock %}

templates/prueba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>